"""
backend/tests/test_outlier_spatial_isolation.py

Regression test suite verifying outlier and noise document spatial isolation:
1. Outliers retain noise classification (cluster_id = 'noise-*', is_boundary = False).
2. Outlier home positions are deterministically assigned to angular gaps between real clusters.
3. Outlier final spatial positions NEVER fall inside any cluster's visual region/expanded convex hull.
4. Normal clustered documents are unaffected (high cohesion, stable silhouette).
5. Generic verification across synthetic corpora with multiple outliers and the sample docs corpus.
"""

import unittest
import math
from pathlib import Path
import numpy as np

from backend.layout.physics import (
    Node,
    simulate,
    compute_home_positions,
    CANVAS_WIDTH,
    CANVAS_HEIGHT,
)
from backend.clustering.pipeline import (
    run_constraint_aware_clustering,
    cluster_embeddings,
)
from backend.tests.fixtures.synthetic_corpora import (
    make_clustered_corpus,
)


def cross_2d(o, a, b):
    return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])


def compute_convex_hull(points: list[tuple[float, float]]) -> list[tuple[float, float]]:
    if len(points) <= 2:
        return points
    sorted_pts = sorted(points, key=lambda p: (p[0], p[1]))
    lower = []
    for p in sorted_pts:
        while len(lower) >= 2 and cross_2d(lower[-2], lower[-1], p) <= 0:
            lower.pop()
        lower.append(p)
    upper = []
    for p in reversed(sorted_pts):
        while len(upper) >= 2 and cross_2d(upper[-2], upper[-1], p) <= 0:
            upper.pop()
        upper.append(p)
    lower.pop()
    upper.pop()
    return lower + upper


def expand_hull_polygon(hull: list[tuple[float, float]], cx: float, cy: float, padding: float = 24.0) -> list[tuple[float, float]]:
    """Exact python port of ClusterRegion.jsx expandHull()."""
    if len(hull) == 0:
        return []
    if len(hull) == 1:
        return hull
    if len(hull) == 2:
        p1, p2 = hull
        dx = p2[0] - p1[0]
        dy = p2[1] - p1[1]
        length = math.hypot(dx, dy) or 1.0
        lat_pad = min(padding, 18.0)
        end_pad = min(padding, 16.0)
        nx = (-dy / length) * lat_pad
        ny = (dx / length) * lat_pad
        ex = (dx / length) * end_pad
        ey = (dy / length) * end_pad
        return [
            (p1[0] - ex + nx, p1[1] - ey + ny),
            (p2[0] + ex + nx, p2[1] + ey + ny),
            (p2[0] + ex - nx, p2[1] + ey - ny),
            (p1[0] - ex - nx, p1[1] - ey - ny),
        ]
    expanded = []
    for p in hull:
        vx = p[0] - cx
        vy = p[1] - cy
        dist = math.hypot(vx, vy)
        if dist < 1e-4:
            expanded.append((p[0] + padding, p[1]))
        else:
            expanded.append((p[0] + (vx / dist) * padding, p[1] + (vy / dist) * padding))
    return expanded


def is_point_inside_polygon(x: float, y: float, poly: list[tuple[float, float]]) -> bool:
    """Ray-casting algorithm to test whether (x, y) is inside polygon."""
    n = len(poly)
    if n < 3:
        return False
    inside = False
    p1x, p1y = poly[0]
    for i in range(n + 1):
        p2x, p2y = poly[i % n]
        if y > min(p1y, p2y):
            if y <= max(p1y, p2y):
                if x <= max(p1x, p2x):
                    if p1y != p2y:
                        xinters = (y - p1y) * (p2x - p1x) / (p2y - p1y) + p1x
                    if p1x == p2x or x <= xinters:
                        inside = not inside
        p1x, p1y = p2x, p2y
    return inside


class TestOutlierSpatialIsolation(unittest.TestCase):
    def test_outlier_noise_classification_preserved(self):
        """Generic outliers generated by HDBSCAN must retain noise-* IDs and not be flagged as boundary."""
        corpus = make_clustered_corpus(n_clusters=3, docs_per_cluster=5, noise_count=3, seed=123)
        res = run_constraint_aware_clustering(corpus.docs, corpus.embeddings)

        cids = res["doc_cluster_ids"]
        flags = res["boundary_flags"]

        # The last 3 are synthetic noise
        for idx in range(15, 18):
            self.assertTrue(cids[idx].startswith("noise-"), f"Document {idx} should have noise- prefix, got {cids[idx]}")
            is_b, sec_cid, sec_w = flags[idx]
            self.assertFalse(is_b, f"Noise document {idx} should not be flagged as boundary document")
            self.assertIsNone(sec_cid)
            self.assertEqual(sec_w, 0.0)

    def test_outlier_home_positions_in_angular_gaps(self):
        """Noise homes must be placed at angular gap bisectors, safely away from all real cluster homes."""
        real_cids = [f"cluster-0{i}" for i in range(4)]
        noise_cids = [f"noise-doc-{i}.pdf" for i in range(3)]
        all_cids = real_cids + noise_cids

        homes = compute_home_positions(all_cids)

        cx, cy = CANVAS_WIDTH / 2.0, CANVAS_HEIGHT / 2.0
        real_angles = [
            math.atan2(homes[cid][1] - cy, homes[cid][0] - cx) % (2.0 * math.pi)
            for cid in real_cids
        ]

        for n_cid in noise_cids:
            nx, ny = homes[n_cid]
            n_angle = math.atan2(ny - cy, nx - cx) % (2.0 * math.pi)

            # Minimum angular distance to any real cluster must be at least 15 degrees (~0.26 rad)
            min_ang_diff = min(
                abs((n_angle - ra + math.pi) % (2.0 * math.pi) - math.pi)
                for ra in real_angles
            )
            self.assertGreater(
                min_ang_diff,
                math.radians(12.0),
                f"Noise anchor {n_cid} is too close to a real cluster (ang diff = {math.degrees(min_ang_diff):.1f}°)",
            )

    def test_synthetic_outliers_never_inside_cluster_hulls(self):
        """For synthetic corpora with multiple clusters and outliers, layout must never place outliers inside any cluster hull."""
        for seed in [42, 99, 2026]:
            corpus = make_clustered_corpus(n_clusters=3, docs_per_cluster=4, noise_count=4, seed=seed)
            res = run_constraint_aware_clustering(corpus.docs, corpus.embeddings)

            cids = res["doc_cluster_ids"]
            b_flags = res["boundary_flags"]

            rng = np.random.default_rng(seed)
            nodes = [
                Node(
                    doc_id=corpus.docs[i]["id"],
                    cluster_id=cids[i],
                    x=CANVAS_WIDTH / 2.0 + float(rng.normal(0, 15.0)),
                    y=CANVAS_HEIGHT / 2.0 + float(rng.normal(0, 15.0)),
                    is_boundary_document=b_flags[i][0],
                    secondary_cluster_id=b_flags[i][1],
                    secondary_weight=b_flags[i][2],
                )
                for i in range(len(corpus.docs))
            ]

            all_cluster_ids = list(set(cids))
            homes = compute_home_positions(all_cluster_ids)
            simulate(nodes, max_iters=250, cluster_home_positions=homes)

            # Group converged nodes by cluster
            clusters: dict[str, list[Node]] = {}
            noise_nodes: list[Node] = []
            for node in nodes:
                if node.cluster_id.startswith("noise-"):
                    noise_nodes.append(node)
                else:
                    clusters.setdefault(node.cluster_id, []).append(node)

            self.assertGreaterEqual(len(noise_nodes), 1, "Should have noise nodes")
            self.assertGreaterEqual(len(clusters), 2, "Should have real clusters")

            # Check point-in-polygon for every noise node against every cluster hull
            for cid, cnodes in clusters.items():
                pts = [(cn.x, cn.y) for cn in cnodes]
                cx_c = sum(p[0] for p in pts) / len(pts)
                cy_c = sum(p[1] for p in pts) / len(pts)
                raw_hull = pts if len(pts) <= 2 else compute_convex_hull(pts)
                expanded_poly = expand_hull_polygon(raw_hull, cx_c, cy_c, padding=24.0)

                for n_node in noise_nodes:
                    inside = is_point_inside_polygon(n_node.x, n_node.y, expanded_poly)
                    self.assertFalse(
                        inside,
                        f"Seed {seed}: Outlier {n_node.doc_id} (pos: {n_node.x:.1f}, {n_node.y:.1f}) "
                        f"was placed INSIDE visual hull of cluster {cid}!",
                    )

    def test_sample_docs_corpus_paper34_spatial_isolation(self):
        """Verify on the actual sample_docs corpus that paper34 and other noise docs are isolated outside all cluster hulls."""
        from backend.api.pipeline import run_pipeline
        sample_dir = Path(__file__).resolve().parent.parent.parent / "data" / "sample_docs"
        if not sample_dir.exists():
            self.skipTest("sample_docs directory not found")

        res = run_pipeline(sample_dir)
        nodes = res["nodes"]

        clusters: dict[str, list[dict]] = {}
        noise_nodes: list[dict] = []
        for n in nodes:
            if n["cluster_id"].startswith("noise-"):
                noise_nodes.append(n)
            else:
                clusters.setdefault(n["cluster_id"], []).append(n)

        # Specifically check paper34
        p34 = next((n for n in nodes if "paper34" in n["doc_id"]), None)
        self.assertIsNotNone(p34, "paper34 should be present in corpus")
        self.assertTrue(p34["cluster_id"].startswith("noise-"), f"paper34 must be noise, got {p34['cluster_id']}")

        # Ensure no noise document is inside any cluster hull
        for cid, cnodes in clusters.items():
            pts = [(cn["x"], cn["y"]) for cn in cnodes]
            cx_c = sum(p[0] for p in pts) / len(pts)
            cy_c = sum(p[1] for p in pts) / len(pts)
            raw_hull = pts if len(pts) <= 2 else compute_convex_hull(pts)
            expanded_poly = expand_hull_polygon(raw_hull, cx_c, cy_c, padding=24.0)

            for n_node in noise_nodes:
                inside = is_point_inside_polygon(n_node["x"], n_node["y"], expanded_poly)
                self.assertFalse(
                    inside,
                    f"Outlier {n_node['doc_id']} is INSIDE visual region of cluster {cid}!",
                )


if __name__ == "__main__":
    unittest.main()
